
#开发环境配置
server:
  port: 8060
spring:
  application:
    #服务名称
    name: chikycloud_admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/chikycloudweb?&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
#    password: chikytech2018cavin
  #------redis
  redis:
    host: 192.168.161.131
#    host: 39.96.7.233
    port: 6379
    password: 123456
    database: 0


mybatis:
  #  typeAliasesPackage: com.jl.music.dao
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: char
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # ͬ同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

myemail:
  # 邮箱服务器端口
  port: 456
  # 邮箱服务器地址
  hostName: smtp.qq.com
  # SSL加密
  sSLOnConnect: true
  # 编码格式
  charset: utf-8
  # 发件人邮箱账号
  emailFromAccount: 1696113170@qq.com
  # 发件人邮箱昵称
  emailFromName: zkCloudAmin
  # 发件人邮箱得到的授权码
  authentication: hikgvkaddyhpdhhb


netty:
  port: 8899
